#!/xbin/bash
#subscribe ya
clear
echo "Selamat datang" $nick
sleep 3
clear
sleep 2
echo "tunggu 10 detik"
bi='\033[34;1m' #biru
ij='\033[32;1m' #ijo
pr='\033[35;1m' #purple
cy='\033[36;1m' #cyan
me='\033[31;1m' #merah
pu='\033[37;1m' #putih
ku='\033[33;1m' #kuning
or='\033[1;38;5;208m' #Orange

clear
echo $me "Akun Ff ya Gan"
sleep 3
echo $bi "Semoga beruntung"
echo $pu "subscribe dulu"
termux-open https://www.youtube.com/channel/UCTMBlJoMW9jaWyiv8oZsjKw
sleep 2
echo "terimakasih sudah subscribe"
echo $pu "Semoga Anda Mendapatkan Akun Yang Anda Cari Cari"
echo $me "Selamat Mechoba"
echo $pu "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
echo $bi "gw gak maksa sanati nanty unsubs gpp"
echo "santai aja "
echo $pu "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
clear
echo " makasih sudah Subscribe"
sleep 2
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "Ini bukan akun hasil phising atau akun hasik hack
Ini Adalah Akun Hasil Beli Jadi Jangan Takut Untuk
mengambilnya " 
"beli langsung ke pemilik soalharga ga penting"
sleep 6
echo $bi "
====[ FACEBOOK ACCOUNT ]====
• Email Facebook :  Putra46@gmail.com
• Password Facebook : putra123$ooko
====[ INFO ACCOUNT ]====
• Nickname : 1680340291
• Level : Level 73
• Pernah Elite Pass : Pernah S2"
sleep 15
echo $or "•> Facebook ACCOUNT <•
Email :> Alma Andriyani
Password :> alma01
• Level : Level 51+
• Pernah Elite Pass : Pernah S5"
sleep 10
echo bi"
•> Facebook ACCOUNT <•
Email :> dinoaku098@gmail.com
Password :> hayukmabar
• Level : Level 33
• Pernah Elite Pass : Pernah S12"
sleep 30
echo "Email :> ranganation8@gmail.com
Password :> elivsayang
• Level : Level 79
• Pernah Elite Pass : Pernah S1"
sleep 17
echo $pu "
Email :> maulanarudiansyah2@gmail.com 
Password :> MaulanaSanti
• Level : Level 70
• Pernah Elite Pass : Pernah S4"
sleep 2
echo $me "Email :> deviarisyara239@gmail.com
Password :> SayangElu
• Level : Level 4
• Pernah Elite Pass : belum pernah"
sleep 30
echo $cy"Email :> radityaadit255@gmail.com
Password :> Mabarduluboz
• Level : Level 39
• Pernah Elite Pass : Pernah S12"
sleep 40
echo "Email :> dancokcokdan98@gmail.com
Password :> RonnyRisma2
• Level : Level 80
• Pernah Elite Pass : Pernah S1"
sleep 1
echo " maaf akun lainya sudah di pakek oleh orang jadi 
cukup sampai disini saja wassalamu'alaikum wr wb
Sy Minta Bantuanya untuk 500 Subscriber "
sleep 1
echo " untuk yang belum dapat bisa nunggu sampai 500
Subscriber (-_-) bukan berarti gw maksa kalian subscribe
yang iklas aja Subscribe {Cukup Sekian Terimakasih}
